### ISSUE TITLE
EncoderGateway error when video file size in bytes exceeds 32-bit Int Max

### ISSUE THREAD

**Issue by hiveuprss** [3speaknetwork/video-encoder#15] opened 2022-07-06 22:25 UTC
Observed in a response returned from the encoderGateway service to encoderGateway client.

jobInfo {"errors":[{"message":"Int cannot represent non 32-bit signed integer value: 2817838452","locations":[{"line":15,"column":15}],"path":["queueJob","job","input","size"]}],"data":{"queueJob":{"reason":"JOB_AVAILABLE","job":{"id":"22590d27-ef46-4b19-9527-a993230920f7","status":"queued","created_at":"2022-07-06T21:50:54.993Z","last_pinged":null,"start_date":null,"completed_at":null,"input":{"format":null,"uri":"https://ipfs.3speak.tv/ipfs/bafybeihdgva3bgzftcn6vm6vuifqctkh25elc2wn6va3frbittci5lehpm","size":null},"result":null,"sync":null,"storageMetadata":{"app":"3speak","key":"vjap55/ngzciiwr/video","type":"video"},"metadata":{"video_owner":"vjap55","video_permlink":"ngzciiwr"}}}}}

2817838452 represents the size of the video. (2.6 GB)

**Comment by vaultec81** [comment] 2022-07-07 00:25
Duplicate of #10. Please put additional details there.

**Closed as completed by vaultec81** 2022-07-07 00:25 UTC
